version: '3.8'
services: 
  db:
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
    networks:
      - app-network
  server:
    build:
      context: .
      dockerfile: .dockerfileServer
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - db
 
networks:
  app-network:
    driver: bridge